development:
  clients::
    default:
      database: eskom_development
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

test:
  clients:
    default:
      database: eskom_test
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

staging:
  sessions:
    clients:
      database: eskom
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

production:
  clients:
    default:
      database: eskom
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true
